"""
Archivist Compression Integration for CRAIID.
This module demonstrates how the Archivist worker would store compression keys 
via low-urgency OAgentD task (long-term storage) as part of the CRAIID pipeline.

Assumes existence of:
 - VLTSCompressor from craiid_compression_core_v3
 - An existing ArchivistWorker class or function that processes insights.
 - Access to OracleAI's task prioritizer via [PRIORITISE] tag (simulated here).

In practice, this would be woven into the Archivist's insight persistence step.
"""

import json
from pathlib import Path
from typing import Dict, Any

# Assuming we can import the compressor; adjust path as needed.
try:
    # If running from backend/craiid or similar
    from craiid_compression_core_v3 import VLTSCompressor
except ImportError:
    # Fallback: try to locate via sys.path
    import sys
    from pathlib import Path
    sys.path.append(str(Path(__file__).parent))
    from craiid_compression_core_v3 import VLTSCompressor


def store_insights_with_compression(insights: Dict[str, Any], 
                                   archive_dir: str = None,
                                   vlts_dir: str = None) -> Dict[str, Any]:
    """
    Process insights and generate/store compression key via low-urgency OAgentD task.
    
    In a real implementation, this function would be called by the Archivist worker
    after generating insights (e.g., personalization candidates, drift segments).
    It creates a compression key from the VLTS archives and stores it alongside 
    the insights for later use by Author during warm-instance reconstruction.
    
    Args:
        insights: Dictionary of insights generated by Archivist (from audit_archives_personal_v2 etc.)
        archive_dir: Path to standard archives (for building symbol map)
        vlts_dir: Path to VLTS archives (to compress and generate key from)
        
    Returns:
        Updated insights dictionary with compression metadata added.
    """
    # Initialize compressor for VLTS archives
    compressor = VLTSCompressor(
        archive_dir=archive_dir,
        vlts_dir=vlts_dir,
        min_frequency=3,   # Can be tuned via procedural memory
        ngram_max=3,
        symbol_length=1
    )
    
    # Build symbol map from archives (this scans VLTS dir if provided, else archive dir)
    build_stats = compressor.build_from_archives() if hasattr(compressor, 'build_from_archives') \
                  else compressor.analyze_corpus([])  # fallback
    
    if not compressor.symbol_map:
        print("[WARN] No compression symbols generated; skipping key storage.")
        insights["compression_key_stored"] = False
        return insights
    
    # Save the compression key as a JSON file (Archivist's long-term storage)
    # In real implementation, this would be submitted via low-urgency OAgentD task:
    # [PRIORITISE: {"fn": "save_compression_key", "payload": {...}, "type": "long_term_storage"}]
    
    key_path = compressor.save_key()  # Uses default vlts_dir/compression_key_<timestamp>.json
    
    # Update insights with compression metadata
    insights["compression"] = {
        "key_stored": True,
        "key_path": key_path,
        "symbol_count": len(compressor.symbol_map),
        "build_stats": build_stats,
        "usage_note": "Author should load this key when reconstructing warm instances from VLTS archives."
    }
    
    print(f"[INFO] Archivist stored compression key: {key_path}")
    print(f"       Symbols generated: {len(compressor.symbol_map)}")
    
    # In a real OAgentD task submission, we would emit something like:
    # [PRIORITISE: {"fn": "archivist_store_compression_key", 
    #               "payload": {"key_path": key_path, "insights_id": insights.get("id")}, 
    #               "type": "long_term_storage", "urgency": "low"}]
    
    return insights


# Example usage (for testing/standalone)
if __name__ == "__main__":
    # Mock insights from Archivist (e.g., output of audit_archives_personal_v2)
    mock_insights = {
        "personalization_candidates": ["verifyfile", "taskp", "oagentd", "periodicworker"],
        "drift_segments": 3,
        "lexical_richness": 0.033,
        "entropy_normalized": 0.85,
        "top_behavioral_command": "verify_chain",
        "timestamp": "2026-06-06T12:00:00Z"
    }
    
    # Run integration (will use default archive/vlts dirs relative to this file)
    updated = store_insights_with_compression(mock_insights)
    
    print("\nUpdated insights with compression metadata:")
    print(json.dumps(updated["compression"], indent=2))